addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: kcTqNMedUFYEkl0+bW8TifbDzlqkFohWUIVzaQDdnIDSYRcLA0FLon5v5msG1ttVTlKUpi5M7Ybw7Aw8sakXGyzO41yf9oLmys+YKyrZQPpZq66DG1jIUZUBVLnVAHhPqEiYfzd60wlDysuTzOCJUBXPSR7xapevZkiRLnZ1SCNOKZwKQ7LblHk96uiAVVL/5iTx9+Ck1g4o4HHno+O1tYALi2PvjaO33nnDcMLGKdjlUhMUD8JWB0F0WvV017uZzKRutIf4G0p5RufD+x7fH+M2wKx/9NqjQexeitqlAuLtkjv9PQmV0U8iD8ZVpRFjrhUMTBt8+mSQm7E2lhWcQnoX+VLmn0xNaECiGW1RRuyDuvVmthsxZtL/dbHUHaD0TQvJl0pSIc4RTvYBZFXTnRPt8towGo9xfl9UOoiGvO60yPOf99qoiMvT7El5UYnlkmonHvWssJkn/9O/Tmt8yMyoS1IKrm86SQlOs18K0fVSaxuhVaF4t6yHpVIiMEi+sqm3Z8mZaMMhF+tZVxeo2lcwl9gFBdDXMFGslKfoNG7fVdlxlwmq7VgZ2C3YkKblakZo5InqfRR8R/bwYoIOdivWbMwb+V0T+hO9j2hV///LwAz7wY1l4aTLDRVBR7Tv9C5fCtM1YEMvMLCOwpUIQRICKl9+sYodBHPjQZCzRUw=
  app: config-server-ondetemjogo
  on:
    repo: ondetemjogo/backend-config-server
cache:
  directories:
  - "$HOME/.m2/repository"