addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: VduYhI++vdxlgpA0YYVl0dhLeyiHdPdUDzmszhQXoM2+9GVL3yODhj/aUqnCVSqf54dEnQVxfezkGgXoFrtXdg4tzxveTAlaZ99tZXkiwL6DGBcwXH+QJcq4QKVecHTo5Fr/cyinZBt4Gye1QYE1Jhopkfgjy/DWF8YT+8ikv/LDlarEHgJjiu9RCXBwz9wM9ZoWK7SInimXhfqabgS+NTeKQMD+fTjCDI6OuDmT06xOP4UxoTVDtRxb6mJhfwp9257G2QR5vr8ENlsF8rwjnbxyavUklCzgBzKekK6hQmLHKNBpdf8v7bknFFg8+UdxW2+5Jbx1eedMoBaF5rOfGB3McdZyKqfov2px2i+EfGGGzA2vlpRHWi97WbrZaDj2rr2Rw7P9rRs80ibziMj3u+r1A2sNJS3DDfBVylIPfMRDQlL+iSY6bQQAMsh2tvRu8qq7WiqeFLTTl+rvcPam+evSzHJpY7+1bNCBmYNNNgVsNJtOlXfhlVZgXSUZFKN1ToV18ErFKuRmBPnazijJkb626AwhlIuL2DCb4yu5DRoyhNAlkPyoRCc0z7JWK54mbeL3+GLfHuLulTsoZKHXQpfjz4tYNTLxMcHLWDAuPcGtJxBe89w89APvj9/xvCTsvEs9tfUBsYax4O0kp2Nmv1FqZuDLn7XCVEqhEN/fJPA=
  app: config-server-ondetemjogo
  on:
    repo: ondetemjogo/backend-config-server
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
    secure: EjTl/d+iKs7N4iLMfdTrBbQp67ObmfEhmXsAIQw7dmnE1/F4vYvdxSIPcN7HhbEqJ12/aySo5fugGsOrXuNFQvON8HcZupIiZ2iD+Utr/Rwnn7vE10imkGJ/4fNfDX2YXgsJ8ZXHb3C5HtU9/jxF6L28Mn9vR62XNcxSS/n+5Bg+NQhFuuhpC14IlJ0ixOlfxVTeqb/NzeU+NR/LExcmMMmOzny20i9CMm3ZifZm9MmKCk9BJ+B4HkIfM+sH4deCnxakIPmnYpgri2FHPzuWJXIjvixMYhTHCnf7g4jLgylVm6bRDgJpfaluTiYTbyLUEeyT7sGyHyeX+x3qn4QmDzDoaP71qMfhISyGFGj2koUwZvSygE3/bSL4fH7/yahFj3QMV+oktov+/RtPgALwI8iqTTOC7kHsSPxhKx7ITnOedHJdf3aawssQFT562F3+4SpZmRbDqQQDONwt8eF/0M3F1KzgBs1RAv8NE+UX2ULoN4uC/WrayLYL9Z4XpODteAFGS0gUqeOK12o4dsWhSAAkobG5kUrtX9l7DY26W2RZCoAM5bH3wdJipkQa69frmw8ndjKcYusZRtqXCgpKoaUnW+OPNAwm4YWVtmRPSMikxfdrdt6AR9e2uHQ8LE5HIxQYP+LoRJku74VRgVwQH7lJ0+mGaN2mi1wLxG0JPOY=
